# register new users to the system
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "username":"Mathers",
    "email":"mather@gmail.com",
    "phoneNumber":"0712345678",
    "password":"Mathers47!"
}

##############
# login existing users
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "emailOrUsername":"marshall@gmail.com",
    "password":"Mathers47!"
}

##############
# add user details
POST http://localhost:4000/auth/add-details/3
Content-Type: application/json

{
    "gender":"male",
    "dob":"2000-01-31",
    "profilePic":"pic/lol.png"
}

###############
# get user by email
GET http://localhost:4000/auth/1/get-by-email
Content-Type: application/json

{
    "email":"lancelot@gmail.com"
}

###############
# get all users
GET http://localhost:4000/auth/1/get-all

###############
# update users
PATCH http://localhost:4000/auth/update/1
Content-Type: application/json

{
    "username":"admin",
    "email":"admin@gmail.net",
    "phoneNumber":"0712345678",
    "password":"@Lancez23",
    "gender":"male",
    "dob":"2000-01-31",
    "profilePic":"pic/lol.png"
}

###############
# deactivate account
PUT http://localhost:4000/auth/deactivate/2ac93804-718c-417e-89d3-0e565dd073db
Content-Type: application/json

{
    "password":"Mathers47!"
}

#############
# delete account
DELETE http://localhost:4000/auth/1/delete
Content-type: application/json

{
    "emailOrUsername":"Mathers"
}