# register new users to the system
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "username":"Lancelot",
    "email":"lancelot@gmail.com",
    "phoneNumber":"0712345678",
    "password":"@Lancez23"
}

##############
# login existing users
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "emailOrUsername":"linc17@gmail.com.ke.net",
    "password":"@Lancez23"
}

##############
# add user details
POST http://localhost:4000/auth/add-details/3
Content-Type: application/json

{
    "gender":"male",
    "dob":"2000-01-31",
    "profilePic":"pic/lol.png"
}

###############
# get user by email
GET http://localhost:4000/auth/1/get-by-email
Content-Type: application/json

{
    "email":"lancelot@gmail.com"
}

###############
# get all users
GET http://localhost:4000/auth/1/get-all

###############
# update users
PATCH http://localhost:4000/auth/update/2
Content-Type: application/json

{
    "username":"Ziggler",
    "email":"zig@gmail.net",
    "phoneNumber":"0712345678",
    "password":"@Lancez23",
    "gender":"male",
    "dob":"2000-01-31",
    "profilePic":"pic/lol.png"
}

###############
# deactivate account
PUT http://localhost:4000/auth/deactivate/dd62e609-bb27-4517-9917-fde01e055bd4

#############
# reactivate account
PATCH http://localhost:4000/auth/reactivate/dd62e609-bb27-4517-9917-fde01e055bd4