# register new users to the system
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "username":"Edward",
    "email":"eduardo@gmail.com",
    "phoneNumber":"0712345678",
    "password":"@Lancez23"
}
