
###
# register new user to the system
POST http://localhost:4000/v1/auth/register
Content-Type: application/json

{
    "first_name":"General",
    "last_name":"Liutenant",
    "user_name":"lance",
    "email":"lance@gmail.com",
    "password":"@Lance25"
}

###
# login existing user
POST http://localhost:4000/v1/auth/login
Content-Type: application/json

{
    "username_or_email":"lance@gmail.com",
    "password":"@Lance25"
}

###
# verify user emails
POST http://localhost:4000/v1/auth/verify-email/73bdcd78-6c24-4ed0-b198-54c63fb15848
###
