import { Request,Response } from "express";
import mysql from 'mysql2/promise'
import {v4 as uid} from 'uuid'
import bcrypt from 'bcrypt'

import { sqlConfig } from "../../config";
import { sqlError } from "../models/db.models";
import { UserRoles, Users, UserDetails } from "../models/users.models";
import { registerSchema,loginEmailSchema,loginUsernameSchema, emailSchema, updateUserSchema, userDetailsSchema } from "../validators/users.validators";

const pool = mysql.createPool(sqlConfig)


export async function registerUser(request:Request,response:Response){
  /*
  * Registers new users into the system
  * id is auto-generated by uuid()
  * user input is validated and checked for errors
  * if none user is added to the system
  * if any error occurrs, user will not be added to system
  * appropriate response message and codes are sent back
  */

  const id = uid()
  // hardcoded to user, incase of new admin, add manually
  const role = UserRoles.user
  const {username,email,phoneNumber,password} = request.body
  
  try {
    const {error} = registerSchema.validate(request.body)
    if (error) {
      return response.status(400).json(error.details[0].message)
    }
    const saltRounds = 10
    const hashedPassword =await bcrypt.hash(password,saltRounds)
    
    const connection = await pool.getConnection()
    const [rows1,fields1] = await connection.query(
      `INSERT INTO users VALUES(
      '${id}',
      '${username}',
      '${email}',
      '${phoneNumber}',
      '${hashedPassword}',
      '${role}',
      DEFAULT,
      DEFAULT,
      0,
      0,
      0
      );`
    )  

    const [rows2,fields2] = await connection.query(
      `SELECT * FROM users
      WHERE id='${id}' AND isDeleted=0;`
    ) 
    connection.release()

    const User = rows2 as Array<Users>

    return response.status(200).json({message:`Congratulations ${User[0].username}! You have successfully been registered on the system.`})
    
  } catch (error:sqlError | any) {
    console.log(error)
    return response.status(500).json({error:`An error occurred: `+error.sqlMessage})
  }
}


export async function loginUser(request:Request,response:Response){
    /*
     * Login already existing users into the system
     * if any error occurrs, user will not be logged into system
     * appropriate response message and codes are sent back
    */

    const {emailOrUsername,password} = request.body
    const emailRegex = /^[\w\.-]+@[a-zA-Z\d\.-]+\.[a-zA-Z]{2,}$/
    
    try {
      const connection = await pool.getConnection()
      if (emailRegex.test(emailOrUsername)) {
        // if email
        const {error} = loginEmailSchema.validate(request.body)

        if (error){
          return response.status(400).json(error.details[0].message)
        }
        // if no error
        const [rows,results] = await connection.query(
          `SELECT * FROM users WHERE
          email='${emailOrUsername}' AND isDeleted=0;`
        )
        const user = rows as Array<Users>
        console.log(user[0])

        if (user) {
          // if user exists
          const validPassword = await bcrypt.compare(password,user[0].hashedPassword)
          
          if(+user[0].isDeactivated===1){
            const [rows,fields] = await connection.query(
              `UPDATE users SET isDeactivated=0 WHERE id='${user[0].id}';`
            )
            return response.status(200).json({messages:`You have successfully reactivated your account. Welcome back!`})
          }
          else if (validPassword){
            return response.status(200).json({message:`Welcome back ${user[0].username}!`})
          } else {
            return response.status(400).json({error:`Oh no. Looks like the passwords do not match, try again?`})
          }
        }
        // if user doesnt exist
        return response.status(400).json({error:`Oops! User does not exist. Try a different email/username?`})
        
      } else if (!emailRegex.test(emailOrUsername)){
        // if not email
        const {error} = loginUsernameSchema.validate(request.body)
        if (error){
          // if error in validation schema
          return response.status(400).json(error.details[0].message)
        }
        // if no error
        const [rows,results] = await connection.query(
          `SELECT * FROM users WHERE
          username='${emailOrUsername}' AND isDeleted=0;`
        )
        const user = rows as Array<Users>
        console.log(user[0])

        if (user) {
          // if user exists
          const validPassword = await bcrypt.compare(password,user[0].hashedPassword)

          if(+user[0].isDeactivated===1){
            const [rows,fields] = await connection.query(
              `UPDATE users SET isDeactivated=0 WHERE id='${user[0].id}';`
            )
            return response.status(200).json({messages:`You have successfully reactivated your account. Welcome back!`})
          } else if (validPassword){
            return response.status(200).json({message:`Welcome back ${user[0].username}!`})
          } else {
            return response.status(400).json({error:`Oh no. Looks like the passwords do not match, try again?`})
          }
        } 
        // if user doesnt exist
        return response.status(400).json({error:`Oops! User does not exist. Try a different email/username?`})
         
      } else {
        return response.status(400).json({error:`Invalid inputs. Please try again?`})
      }   
    } catch (error:sqlError | any) {
      return response.status(500).json({error:`An error occurred: `+error.sqlMessage})
    }
}


export async function addUserDetails(request:Request<{id:string}>,response:Response){

  const id = uid()
  const userId = request.params.id
  const { gender,dob,profilePic } = request.body

  try {
      const connection = await pool.getConnection()
      const { error } = userDetailsSchema.validate(request.body)
      if(error){
        return response.status(400).json(error.details[0].message)        
      }
      const [rows,fields] = await connection.query(
          `INSERT INTO userDetails VALUES(
          '${id}',
          '${userId}',
          '${gender}',
          '${dob}',
          '${profilePic}',
          DEFAULT
          );`
      )
      const userDetails = rows as Array<UserDetails>
      console.log(userDetails)

      return response.status(200).json({success:`Congratulations! You have succesfully updated your details.`})
      
  } catch (error:sqlError | any) {
      return response.status(500).json({error:`An error occurred: `+error.sqlMessage})
      
  }
}


export async function deactivateAccount(request:Request<{id:string}>,response:Response){
  /*
   * deactivates a users account
   * if user does not reativate back in 7 days, acc is permanently deleted
   * appropriate error messages are returned 
   */
  const id = request.params.id
  const { password } = request.body
  try {
    const connection = await pool.getConnection()
    const [rows1,results1] = await pool.query(
      `SELECT * FROM users WHERE id='${id}' AND isDeleted=0;`
    )
    const user = rows1 as Array<Users>
    console.log(user)
    if (user[0]){
      const validPassword = await bcrypt.compare(password, user[0].hashedPassword)
      console.log(`pass bool: ${validPassword}`)
      if (validPassword) {
        const [rows2,results2] = await pool.query(
          `UPDATE users SET isDeactivated=1 WHERE id='${id}' AND isDeleted=0;`
        )
        return response.status(200).json({message:`You have successfully deactivated your account. It will be permanently deleted in 7 days.`})
      }
      return response.status(400).json({message:`Oh no! Looks like the passwords do not match. Try again?`})
    }
    return response.status(400).json({error:`Oops!Looks like that user does not exist. Try again?`})
    
  } catch (error:sqlError | any) {
    return response.status(500).json({error:`An error occured: `+error.sqlError})
  }

}
