import { Request,Response } from "express";
import mysql from 'mysql2/promise'
import {v4 as uid} from 'uuid'

import { sqlConfig } from "./config";

export async function registerUser(request:Request,response:Response){
    /*
     * Registers new users into the system
     * id is auto-generated by uuid() for security
     * if any error occurrs, user will not be added to system
     * appropriate response message and codes are sent back
    */

    const id = uid()
    const {username,email,phoneNumber,password} = request.body
    
    try {
        const connection = await mysql.createConnection(sqlConfig)
        const [results,fields] = await connection.query(
          `INSERT INTO userBasicInfo VALUES(
          '${id}',
          '${username}',
          '${email}',
          '${phoneNumber}',
          '${password}',
          DEFAULT,
          0,
          0
          );
          `
        )  
        console.log(results)
      } catch (error) {
          console.log(error)
      }
}
